spring:
  thymeleaf:
    cache: false
  profiles:
    active: production
    
amazon:
  associatedId: dreamerfable
  
management:
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always 
      
info:
  contactEmail: dreamerfable@gmail.com  
---
spring:
  profiles: development
  
logging:
  level:
    root: DEBUG
    
---
spring:
  profiles: production

logging:
  level:
    root: INFO    
