spring:
  thymeleaf:
    cache: false
  profiles:
    active: production
    
amazon:
  associatedId: dreamerfable
  
    
---
spring:
  profiles: development
  
logging:
  level:
    root: DEBUG
    
---
spring:
  profiles: production

logging:
  level:
    root: WARN     
